name: Build (Manual)

on:
  workflow_dispatch:  # run it from the Actions tab when you want

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Optional but helpful to fail early if restore has issues
      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build (Release)
        run: dotnet build -c Release --no-restore

      # Publish a framework-dependent build into out/win-x64
      # (If you prefer self-contained, add: -r win-x64 --self-contained true)
      - name: dotnet publish
        run: dotnet publish -c Release -o out/win-x64 --no-build

      - name: Zip artifact
        shell: pwsh
        run: |
          $OutDir = Resolve-Path 'out/win-x64'
          New-Item -ItemType Directory -Force -Path 'artifacts' | Out-Null
          $ZipPath = Join-Path 'artifacts' 'LGSTrayBattery.zip'
          if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }
          Compress-Archive -Path "$OutDir\*" -DestinationPath $ZipPath
          "ZIP_PATH=$ZipPath" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LGSTrayBattery-build
          path: ${{ env.ZIP_PATH }}
          if-no-files-found: error
