name: Build

on:
  workflow_dispatch:  # manual run

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Build & package with publish.py (self-contained)
      - name: Build & package
        shell: pwsh
        run: |
          $commit_ts = git show --no-patch --format=%at
          $ymd       = ([DateTimeOffset]::FromUnixTimeSeconds($commit_ts)).ToString("yyyyMMdd")

          # Use a SemVer-safe suffix: "-local.YYYYMMDD"
          # Pass as a single token (no spaces) to avoid argparse issues.
          python .\publish.py --version-suffix=-local.$ymd

          if (-not (Test-Path .\bin\Release\publish)) {
            throw "Publish folder not created. Did publish.py fail?"
          }

          # Pick up any zip that publish.py produced (standalone / framedep)
          $zips = Get-ChildItem .\bin\Release\publish -Filter *.zip -Recurse
          if ($zips.Count -eq 0) {
            throw "No zip artifacts found under bin/Release/publish."
          }

          # Store list for the upload step
          $paths = ($zips | ForEach-Object { $_.FullName }) -join "`n"
          Set-Content -Path $env:GITHUB_OUTPUT -Value "paths<<EOF`n$paths`nEOF" -Encoding utf8

        id: build_step

      - name: Upload artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: LGSTrayBattery-build
          path: |
            ${{ steps.build_step.outputs.paths }}
          if-no-files-found: error
