name: Build

on:
  workflow_dispatch:   # run manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build & Package
        shell: pwsh
        run: |
          python .\publish.py --version-suffix "-local"
          $zip = Get-Item ./bin/Release/publish/*.zip -ErrorAction Stop
          echo "ZIP_PATH=$($zip.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LGSTrayBattery-build
          path: ${{ env.ZIP_PATH }}
